# Generated by Django 5.2.17 on 2026-09-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('task_type', models.CharField(blank=True, max_length=64)),
                ('result_json', models.JSONField()),
                ('verification_passed', models.BooleanField(null=True)),
                ('verification_json', models.JSONField(blank=True, null=True)),
                ('user_feedback', models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down')], max_length=16, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]